apiVersion: apps/v1
kind: Deployment
metadata:
  name: dash-analytics-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dash-analytics-app
  template:
    metadata:
      labels:
        app: dash-analytics-app
    spec:
      containers:
      - name: dash-analytics-container
        image: arunvel1988/ecomm-analytics:demo-v1
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: kafka-tls-volume
          mountPath: /etc/kafka  # Mount the secret at this path inside the container
          readOnly: true  # Ensure the certificates are read-only
      volumes:
      - name: kafka-tls-volume
        secret:
          secretName: aiven-kafka-tls  # Name of the secret that holds your Kafka TLS certificates
          items:
            - key: ca.pem
              path: ca.pem
            - key: service.cert
              path: service.cert
            - key: service.key
              path: service.key
---
apiVersion: v1
kind: Service
metadata:
  name: dash-analytics-service
spec:
  selector:
    app: dash-analytics-app
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP  # Use NodePort or LoadBalancer if required by your environment
